### ISSUE TITLE
Modernize codebase

### ISSUE THREAD

**Issue by KapJI** [simon-weber/gpsoauth#26]
We're using `gpsoauth` in [glocaltokens](https://github.com/leikoilja/glocaltokens) and [google_home](https://github.com/leikoilja/ha-google-home) Home Assistant integration.

I want to make these projects strictly type checked. And for this we need `gpsoauth` also type checked.

There are 2 options how to do that:
1. Write type stubs in `glocaltokens` repo. But then only this project will benefit from it.
2. Ship typing information with `gpsoauth`. This way everyone who uses `gpsoauth` can benefit for it. But this requires major changes in this repo.

Just out of my head this will be:
- Drop Python 2 support to use modern format of type hints. Python 2 is deprecated and we can say current version is the last one which supports Python 2.
- Setup testing with Github Actions, especially with `mypy` to make sure these type hints are correct.
- Also it's nice to setup some linters e.g. `black`, `isort`, `flake8` and `pylint`.
- Use [Poetry](https://python-poetry.org/) to manage dependencies, build and publish new packages. It's a modern way to manage Python packages and it can replace `setuptools` and `tox`.

I can do all of this if you're willing to support me and review my pull requests in a timely manner.

@simon-weber  what do you think?

**Comment by simon-weber** [comment]
> it's nice to setup some linters

👍 I've been using [pre-commit](https://github.com/simon-weber/repominder/blob/master/.pre-commit-config.yaml) in some of my other projects if you want to copy/tweak that.

> Use Poetry to manage dependencies

I haven't tried poetry since I've been happy with pip-tools (I usually use it [like this](https://github.com/simon-weber/repominder/blob/683099d3125af8fdb448bf03d1e7c874517835d7/Makefile#L11-L12)). It sounds like poetry does more; if it's something you're familiar with and like I'm happy to give it a try.

👍 on the rest!

> if you're willing to support me and review my pull requests in a timely manner.

Sure! I can probably get to PRs within a day or two on average and a week at the latest. And since I'm not really using gpsoauth myself these days I'll probably be less opinionated as to what gets merged 😁

**Comment by KapJI** [comment]
Awesome, thank you! I'll start working on this in the next couple of days then 🙂
