### ISSUE TITLE
What are android_id & client_sig ?

### ISSUE THREAD

**Issue by derekantrican** [simon-weber/gpsoauth#71]
I'm trying to follow the docs to get this set up on a new computer (using gpsoauth via https://github.com/kiwiz/gkeepapi). I see the code snippets in the README, but it looks like `android_id` and `client_sig` have placeholder values in the README snippet? What are these variables and what values should I be putting in? (I don't see them explained in any docs - please let me know if I missed it)

Since I'm using this for the gkeepapi, should I change `app` to `com.google.android.keep` (or something similar)?

**Comment by simon-weber** [comment]
You shouldn't need to do anything special if you're using a library that wraps gpsoauth. [gkeepapi already has the app + client_sig set](https://github.com/kiwiz/gkeepapi/blob/d56a9e388dc66a51ec7d0dd37e443c2beb37f5a7/src/gkeepapi/__init__.py#L140-L164) for Keep. I'd recommend trying their instructions [here](https://gkeepapi.readthedocs.io/en/latest/#obtaining-a-master-token) rather than trying to use gpsoauth directly.

For the device id, you can make one up or try to reuse one from an existing device. They used to be listed in Google's security page under something like active devices.

**Comment by derekantrican** [comment]
Thanks. I don't have docker installed so I was following the link in their instructions that links to here: https://github.com/simon-weber/gpsoauth#alternative-flow . That's where I was getting confused. I then tried following https://github.com/rukins/gpsoauth-java/blob/b74ebca999d0f5bd38a2eafe3c0d50be552f6385/README.md#receiving-an-authentication-token and none of that worked for me.

I'll try installing docker and going the docker route
